from enum import StrEnum


class ErrorCode(StrEnum):
    # Auth/Authz
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_PERMISSION_DENIED = "AUTH_PERMISSION_DENIED"

    # Room/Connection
    ROOM_NOT_FOUND = "ROOM_NOT_FOUND"
    ROOM_FULL = "ROOM_FULL"
    DUPLICATE_CONNECTION = "DUPLICATE_CONNECTION"

    # State Machine
    STATE_LOCK_TIMEOUT = "STATE_LOCK_TIMEOUT"
    OUT_OF_TURN = "OUT_OF_TURN"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    VERSION_MISMATCH = "VERSION_MISMATCH"

    # Command Validation
    INVALID_PATH = "INVALID_PATH"
    OUT_OF_RANGE = "OUT_OF_RANGE"
    UNKNOWN_TARGET = "UNKNOWN_TARGET"
    UNKNOWN_CHARACTER = "UNKNOWN_CHARACTER"
    UNKNOWN_WEAPON = "UNKNOWN_WEAPON"
    INVALID_DICE_DISTRIBUTION = "INVALID_DICE_DISTRIBUTION"
    INVALID_ACTION_SEQUENCE = "INVALID_ACTION_SEQUENCE"

    # Resources
    INSUFFICIENT_MP = "INSUFFICIENT_MP"
    INSUFFICIENT_KATASHIRO = "INSUFFICIENT_KATASHIRO"
    NO_LINE_OF_SIGHT = "NO_LINE_OF_SIGHT"

    # Interrupts
    PENDING_NOT_FOUND = "PENDING_NOT_FOUND"
    PENDING_EXPIRED = "PENDING_EXPIRED"
    DUPLICATE_REQUEST = "DUPLICATE_REQUEST"

    # AI
    AI_FALLBACK = "AI_FALLBACK"
    AI_PARSE_ERROR = "AI_PARSE_ERROR"
    AI_BACKEND_UNAVAILABLE = "AI_BACKEND_UNAVAILABLE"

    # Scenario
    SCENARIO_VALIDATION_FAILED = "SCENARIO_VALIDATION_FAILED"
    SCENARIO_NOT_FOUND = "SCENARIO_NOT_FOUND"

    # Internal
    INTERNAL_ERROR = "INTERNAL_ERROR"
