from enum import Enum


class ErrorCode(str, Enum):
    # Auth / room
    ROOM_NOT_FOUND = "ROOM_NOT_FOUND"
    ROOM_FULL = "ROOM_FULL"
    INVALID_TOKEN = "INVALID_TOKEN"
    PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND"

    # Session / state
    VERSION_MISMATCH = "VERSION_MISMATCH"
    NOT_YOUR_TURN = "NOT_YOUR_TURN"
    SESSION_BUSY = "SESSION_BUSY"

    # Turn action validation
    INVALID_PATH = "INVALID_PATH"
    INVALID_DICE_DISTRIBUTION = "INVALID_DICE_DISTRIBUTION"
    INVALID_TARGET = "INVALID_TARGET"
    OUT_OF_RANGE = "OUT_OF_RANGE"
    NO_LINE_OF_SIGHT = "NO_LINE_OF_SIGHT"

    # Pending
    PENDING_NOT_FOUND = "PENDING_NOT_FOUND"
    PENDING_EXPIRED = "PENDING_EXPIRED"

    # Internal
    INTERNAL_ERROR = "INTERNAL_ERROR"
    SCHEMA_VIOLATION = "SCHEMA_VIOLATION"


class CloseCode(int, Enum):
    NORMAL = 1000
    INVALID_TOKEN = 4001
    ROOM_NOT_FOUND = 4004
    SESSION_LOST = 4010
    BACKPRESSURE = 4011
