from enum import StrEnum


class ErrorCode(StrEnum):
    # 認証・認可
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_PERMISSION_DENIED = "AUTH_PERMISSION_DENIED"

    # ルーム・接続
    ROOM_NOT_FOUND = "ROOM_NOT_FOUND"
    ROOM_FULL = "ROOM_FULL"
    DUPLICATE_CONNECTION = "DUPLICATE_CONNECTION"

    # ステートマシン
    STATE_LOCK_TIMEOUT = "STATE_LOCK_TIMEOUT"
    OUT_OF_TURN = "OUT_OF_TURN"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    VERSION_MISMATCH = "VERSION_MISMATCH"

    # コマンドバリデーション
    INVALID_PATH = "INVALID_PATH"
    OUT_OF_RANGE = "OUT_OF_RANGE"
    UNKNOWN_TARGET = "UNKNOWN_TARGET"
    UNKNOWN_CHARACTER = "UNKNOWN_CHARACTER"
    UNKNOWN_WEAPON = "UNKNOWN_WEAPON"
    INVALID_DICE_DISTRIBUTION = "INVALID_DICE_DISTRIBUTION"
    INVALID_ACTION_SEQUENCE = "INVALID_ACTION_SEQUENCE"
    INVALID_MESSAGE = "INVALID_MESSAGE"

    # リソース
    INSUFFICIENT_MP = "INSUFFICIENT_MP"
    INSUFFICIENT_KATASHIRO = "INSUFFICIENT_KATASHIRO"
    NO_LINE_OF_SIGHT = "NO_LINE_OF_SIGHT"

    # 割り込み
    PENDING_NOT_FOUND = "PENDING_NOT_FOUND"
    PENDING_EXPIRED = "PENDING_EXPIRED"
    DUPLICATE_REQUEST = "DUPLICATE_REQUEST"

    # AI
    AI_FALLBACK = "AI_FALLBACK"
    AI_PARSE_ERROR = "AI_PARSE_ERROR"
    AI_BACKEND_UNAVAILABLE = "AI_BACKEND_UNAVAILABLE"

    # シナリオ
    SCENARIO_VALIDATION_FAILED = "SCENARIO_VALIDATION_FAILED"
    SCENARIO_NOT_FOUND = "SCENARIO_NOT_FOUND"

    # 内部
    INTERNAL_ERROR = "INTERNAL_ERROR"


class CloseCode:
    NORMAL = 1000
    CLIENT_LEAVING = 1001
    AUTH_FAILED = 4000
    SESSION_LOST_TIMEOUT = 4001
    SESSION_LOST_RESTART = 4002
    BACK_PRESSURE = 4003
    RATE_LIMITED = 4004
    DUPLICATE_CONNECTION = 4005
