"""Pydantic data models for the GM domain (Phase 1)."""

from .character import Character, FirstMoveMode, NPCEvasionPolicy, StatusEffect
from .constants import (
    DIFFICULTY_TABLE,
    AdditionalStyle,
    MeleeStyle,
    RangeClass,
    RangedStyle,
    clamp_difficulty,
    lookup_range_difficulty,
)
from .damage import AbilityBonus, DamageFormula, DamageSpec
from .event import GameEvent, TurnSummary
from .pending import (
    DeathAvoidanceRequest,
    EvasionRequest,
    IncomingAttack,
)
from .scenario import (
    ActionShowNarrative,
    ActionSpawnEnemy,
    FailureAllPCsDefeated,
    FailureCondition,
    FailureRoundLimit,
    Scenario,
    ScenarioAction,
    ScenarioCharacter,
    ScenarioEvent,
    Trigger,
    TriggerCharacterDies,
    TriggerEnterZone,
    TriggerRoundReached,
    VictoryAllEnemiesDefeated,
    VictoryCondition,
    VictoryReachZone,
)
from .skill import (
    SKILL_REQUIREMENTS,
    SkillRequirement,
    character_meets_requirement,
)
from .state import GamePhase, GameState, MachineState, PendingAction
from .turn_action import (
    MainAction,
    MeleeAttack,
    Movement,
    OtherAction,
    PegAttack,
    RangedAttack,
    Skip,
    TurnAction,
)
from .weapon import Weapon, WeaponCategory

__all__ = [
    "DIFFICULTY_TABLE",
    "SKILL_REQUIREMENTS",
    "AbilityBonus",
    "ActionShowNarrative",
    "ActionSpawnEnemy",
    "AdditionalStyle",
    "Character",
    "DamageFormula",
    "DamageSpec",
    "DeathAvoidanceRequest",
    "EvasionRequest",
    "FailureAllPCsDefeated",
    "FailureCondition",
    "FailureRoundLimit",
    "FirstMoveMode",
    "GameEvent",
    "GamePhase",
    "GameState",
    "IncomingAttack",
    "MachineState",
    "MainAction",
    "MeleeAttack",
    "MeleeStyle",
    "Movement",
    "NPCEvasionPolicy",
    "OtherAction",
    "PegAttack",
    "PendingAction",
    "RangeClass",
    "RangedAttack",
    "RangedStyle",
    "Scenario",
    "ScenarioAction",
    "ScenarioCharacter",
    "ScenarioEvent",
    "Skip",
    "SkillRequirement",
    "StatusEffect",
    "Trigger",
    "TriggerCharacterDies",
    "TriggerEnterZone",
    "TriggerRoundReached",
    "TurnAction",
    "TurnSummary",
    "VictoryAllEnemiesDefeated",
    "VictoryCondition",
    "VictoryReachZone",
    "Weapon",
    "WeaponCategory",
    "character_meets_requirement",
    "clamp_difficulty",
    "lookup_range_difficulty",
]
