// AUTO-GENERATED — do not edit manually. Run: bash packages/ws-schema/scripts/generate.sh

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ClientMessage = JoinRoom | SubmitTurnAction | SubmitEvasion | SubmitDeathAvoidance | PlayerStatement;
export type Action = "join_room";
export type PlayerId = string;
export type RoomId = string;
export type AuthToken = string;
export type LastSeenEventId = number;
export type Action1 = "submit_turn_action";
export type PlayerId1 = string;
export type RoomId1 = string;
export type ClientRequestId = string;
export type ExpectedVersion = number;
export type Action2 = "submit_evasion";
export type PlayerId2 = string;
export type RoomId2 = string;
export type ClientRequestId1 = string;
export type PendingId = string;
export type DiceResult = number;
export type Action3 = "submit_death_avoidance";
export type PlayerId3 = string;
export type RoomId3 = string;
export type ClientRequestId2 = string;
export type PendingId1 = string;
export type UseKatashiro = boolean;
export type Action4 = "player_statement";
export type PlayerId4 = string;
export type RoomId4 = string;
export type ClientRequestId3 = string;
export type Text = string;

export interface JoinRoom {
  action: Action;
  player_id: PlayerId;
  room_id: RoomId;
  auth_token: AuthToken;
  last_seen_event_id: LastSeenEventId;
}
export interface SubmitTurnAction {
  action: Action1;
  player_id: PlayerId1;
  room_id: RoomId1;
  client_request_id: ClientRequestId;
  expected_version: ExpectedVersion;
  turn_action: TurnAction;
}
export interface TurnAction {
  [k: string]: unknown;
}
export interface SubmitEvasion {
  action: Action2;
  player_id: PlayerId2;
  room_id: RoomId2;
  client_request_id: ClientRequestId1;
  pending_id: PendingId;
  dice_result: DiceResult;
}
export interface SubmitDeathAvoidance {
  action: Action3;
  player_id: PlayerId3;
  room_id: RoomId3;
  client_request_id: ClientRequestId2;
  pending_id: PendingId1;
  use_katashiro: UseKatashiro;
}
export interface PlayerStatement {
  action: Action4;
  player_id: PlayerId4;
  room_id: RoomId4;
  client_request_id: ClientRequestId3;
  text: Text;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ServerMessage =
  | SessionRestore
  | StateUpdate
  | StateFull
  | GmNarrative
  | GameEventMessage
  | AiThinking
  | EvadeRequired
  | AiFallbackNotice
  | SessionLost
  | ErrorMessage;
export type Type = "session_restore";
export type EventId = number;
export type Timestamp = string;
export type Mode = "incremental" | "full_sync";
export type MissedEvents = {
  [k: string]: unknown;
}[];
export type Type1 = "state_update";
export type EventId1 = number;
export type Timestamp1 = string;
export type Version = number;
export type Patch = {
  [k: string]: unknown;
}[];
export type Type2 = "state_full";
export type EventId2 = number;
export type Timestamp2 = string;
export type Version1 = number;
export type Type3 = "gm_narrative";
export type EventId3 = number;
export type Timestamp3 = string;
export type Text = string;
export type IsStreaming = boolean;
export type Type4 = "event";
export type EventId4 = number;
export type Timestamp4 = string;
export type EventName = string;
export type Type5 = "ai_thinking";
export type EventId5 = number;
export type Timestamp5 = string;
export type Stage = string;
export type Type6 = "evade_required";
export type EventId6 = number;
export type Timestamp6 = string;
export type PendingId = string;
export type AttackerId = string;
export type TargetId = string;
export type DeadlineSeconds = number;
export type Type7 = "ai_fallback_notice";
export type EventId7 = number;
export type Timestamp7 = string;
export type Reason = string;
export type Type8 = "session_lost";
export type EventId8 = number;
export type Timestamp8 = string;
export type Reason1 = string;
export type Type9 = "error";
export type EventId9 = number;
export type Timestamp9 = string;
export type Code = string;
export type Message = string;
export type Detail = {
  [k: string]: unknown;
} | null;
export type ClientRequestId = string | null;

export interface SessionRestore {
  type: Type;
  event_id: EventId;
  timestamp: Timestamp;
  mode: Mode;
  current_state: CurrentState;
  missed_events?: MissedEvents;
}
export interface CurrentState {
  [k: string]: unknown;
}
export interface StateUpdate {
  type: Type1;
  event_id: EventId1;
  timestamp: Timestamp1;
  version: Version;
  patch: Patch;
}
export interface StateFull {
  type: Type2;
  event_id: EventId2;
  timestamp: Timestamp2;
  version: Version1;
  state: State;
}
export interface State {
  [k: string]: unknown;
}
export interface GmNarrative {
  type: Type3;
  event_id: EventId3;
  timestamp: Timestamp3;
  text: Text;
  is_streaming?: IsStreaming;
}
export interface GameEventMessage {
  type: Type4;
  event_id: EventId4;
  timestamp: Timestamp4;
  event_name: EventName;
  payload: Payload;
}
export interface Payload {
  [k: string]: unknown;
}
export interface AiThinking {
  type: Type5;
  event_id: EventId5;
  timestamp: Timestamp5;
  stage: Stage;
}
export interface EvadeRequired {
  type: Type6;
  event_id: EventId6;
  timestamp: Timestamp6;
  pending_id: PendingId;
  attacker_id: AttackerId;
  target_id: TargetId;
  deadline_seconds: DeadlineSeconds;
}
export interface AiFallbackNotice {
  type: Type7;
  event_id: EventId7;
  timestamp: Timestamp7;
  reason: Reason;
}
export interface SessionLost {
  type: Type8;
  event_id: EventId8;
  timestamp: Timestamp8;
  reason: Reason1;
}
export interface ErrorMessage {
  type: Type9;
  event_id: EventId9;
  timestamp: Timestamp9;
  code: Code;
  message: Message;
  detail?: Detail;
  client_request_id?: ClientRequestId;
}
